### ISSUE TITLE
v2ex 脚本签到的问题

### ISSUE THREAD

**Issue by wdd2007** [lord63/a_bunch_of_code#18]
{
    "username" = 'xxxx',
    "password" = 'xxxx',
    "log_directory" = '/path/to/save/logfile/',
    "count" = 5   # 查看默认的最近的情况的天数，可以自己设置
}

这是 json 格式？ 不是的吧。

**Comment by lord63** [comment]
Orz， 是我写错了。

**Comment by lord63** [comment]
@wdd2007 改了之后请问能正常使用么？
